### ISSUE TITLE
tensorflow pytorch and moleculekit conflict

### ISSUE THREAD

**Issue by kenndshi** [AspirinCode/GENiPPI#1]
I am trying to install the repo, but there are conflicts with the requirements
torch==1.7.1 requires cuda version 11.0 and cudnn 0.8.2 where tensorflow=2.5.0 requires cuda 11.2 and cudnn 8.1.
Can you please help me in solving this error?

**Comment by AspirinCode** [comment]
`conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch`
`pip install tensorflow-gpu==2.5.0`

**Comment by AspirinCode** [comment]
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch
pip install tensorflow-gpu==2.5.0

**Comment by kenndshi** [comment]
Thanks for the reply.
I have one more question if you may.
I encountered this error No such file or directory:example.npy  and then
'./gPPMol/smile_str_resatom_dict_rest.npy'.
I created example .npy file by myself filling it with smiles, but I didn't
figure out what to do with the missing file.
I would be very grateful if you help me run your repo and if so I am
looking forward to including results and citing you in my research.
Thanks in advance
