### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './gPPMol/file_id.txt'

### ISSUE THREAD

**Issue by kenndshi** [AspirinCode/GENiPPI#2]
I got this error while running notbeook
./interface.rinterface ./interface.linterface
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    from gPPMol.comgen import decode_smiles
  File "/home/nikola/Desktop/tik/GENiPPI/gPPMol/comgen.py", line 7, in <module>
    from gPPMol.gene import *
  File "/home/nikola/Desktop/tik/GENiPPI/gPPMol/gene.py", line 119, in <module>
    with open("./gPPMol/file_id.txt","r") as f :
FileNotFoundError: [Errno 2] No such file or directory: './gPPMol/file_id.txt'

**Comment by kenndshi** [comment]
Also I got this error while running train.py.

FileNotFoundError: [Errno 2] No such file or directory: './gPPMol/example.npy'

**Comment by AspirinCode** [comment]
> Also I got this error while running train.py.
> 
> FileNotFoundError: [Errno 2] No such file or directory: './gPPMol/example.npy'


`Contact by e-mail：drugai@hotmail.com`

**Comment by AspirinCode** [comment]
> I got this error while running notbeook ./interface.rinterface ./interface.linterface Traceback (most recent call last): File "run.py", line 47, in from gPPMol.comgen import decode_smiles File "/home/nikola/Desktop/tik/GENiPPI/gPPMol/comgen.py", line 7, in from gPPMol.gene import * File "/home/nikola/Desktop/tik/GENiPPI/gPPMol/gene.py", line 119, in with open("./gPPMol/file_id.txt","r") as f : FileNotFoundError: [Errno 2] No such file or directory: './gPPMol/file_id.txt'

`Contact by e-mail：drugai@hotmail.com`
